title: Mixed Reality Media Thesis
author: Martin Zier
description: This is the website to the Mixed Reality Media Thesis written by Martin Zier
baseurl: "/MixedRealityMedia-Thesis"
url: "https://miosblog.de"
lang: en
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - jekyll-p5-guide.gemspec

# ganalytics
google_analytics:

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year:month:day:title/

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
